"""empty message

Revision ID: e62edae63cf8
Revises: fe63d76395c2
Create Date: 2023-05-29 15:37:27.078940

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e62edae63cf8'
down_revision = 'fe63d76395c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_respons', schema=None) as batch_op:
        batch_op.drop_index('fk_quiz_respons_quiz_question1_idx')
        batch_op.drop_index('fk_quiz_respons_user1_idx')

    op.drop_table('quiz_respons')
    with op.batch_alter_table('quiz_question', schema=None) as batch_op:
        batch_op.drop_index('fk_quiz_question_category1_idx')
        batch_op.drop_index('fk_quiz_question_type_idx')

    op.drop_table('quiz_question')
    op.drop_table('recyclebin')
    with op.batch_alter_table('quiz__question', schema=None) as batch_op:
        batch_op.alter_column('alt1',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False,
               existing_server_default=sa.text("'Legg til et spørsmål'"))
        batch_op.create_foreign_key(None, 'category', ['category_id'], ['id'])
        batch_op.create_foreign_key(None, 'type', ['type_id'], ['id'])

    with op.batch_alter_table('type', schema=None) as batch_op:
        batch_op.drop_index('category_UNIQUE')
        batch_op.create_index(batch_op.f('ix_type_category'), ['category'], unique=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('firstname',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('lastname',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('isAdmin',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.SmallInteger(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.drop_index('username_UNIQUE')
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', mysql.VARCHAR(length=200), nullable=True))
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.create_index('username_UNIQUE', ['username'], unique=False)
        batch_op.alter_column('isAdmin',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(display_width=4),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('lastname',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=45),
               existing_nullable=True)
        batch_op.alter_column('firstname',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=45),
               existing_nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=45),
               existing_nullable=True)
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_type_category'))
        batch_op.create_index('category_UNIQUE', ['category'], unique=False)

    with op.batch_alter_table('quiz__question', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('alt1',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True,
               existing_server_default=sa.text("'Legg til et spørsmål'"))

    op.create_table('recyclebin',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('category', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('definition', mysql.MEDIUMTEXT(), nullable=False),
    sa.Column('solution', mysql.MEDIUMTEXT(), nullable=False),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('quiz_question',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('definition', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('active', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('category_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('alt1', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('alt2', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('alt3', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('alt4', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('alt5', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('alt6', mysql.VARCHAR(length=200), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='fk_quiz_question_category1'),
    sa.ForeignKeyConstraint(['type_id'], ['type.id'], name='fk_quiz_question_type'),
    sa.PrimaryKeyConstraint('id', 'type_id', 'category_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('quiz_question', schema=None) as batch_op:
        batch_op.create_index('fk_quiz_question_type_idx', ['type_id'], unique=False)
        batch_op.create_index('fk_quiz_question_category1_idx', ['category_id'], unique=False)

    op.create_table('quiz_respons',
    sa.Column('id_qst', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('id_user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('quiz_answer', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('quiz_status', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True),
    sa.Column('quiz_comment', mysql.MEDIUMTEXT(), nullable=True),
    sa.ForeignKeyConstraint(['id_qst'], ['quiz_question.id'], name='fk_quiz_respons_quiz_question1'),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], name='fk_quiz_respons_user1'),
    sa.PrimaryKeyConstraint('id_qst', 'id_user'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('quiz_respons', schema=None) as batch_op:
        batch_op.create_index('fk_quiz_respons_user1_idx', ['id_user'], unique=False)
        batch_op.create_index('fk_quiz_respons_quiz_question1_idx', ['id_qst'], unique=False)

    # ### end Alembic commands ###
