"""empty message

Revision ID: fe63d76395c2
Revises: c7e9af21a8da
Create Date: 2023-05-25 17:59:39.541817

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fe63d76395c2'
down_revision = 'c7e9af21a8da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz__question', schema=None) as batch_op:
        batch_op.drop_column('alt7')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz__question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alt7', mysql.VARCHAR(length=200), nullable=True))

    # ### end Alembic commands ###
